server {
    listen 80;
    root /app;
    index index.html;

    location / {
        if ($request_uri = "/index.html") { return 301 /; }
        rewrite ^/([a-zA-Z-]+)\.(php|html)$ /$1 permanent;
        try_files $uri $uri.html $uri/ =404;
    }
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}
